# Generated by Django 5.2.5 on 2025-08-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_spotifytoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='spotify_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
