# Generated by Django 5.2.5 on 2025-08-11 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_alter_review_rating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='album',
            unique_together={('title', 'artist')},
        ),
    ]
